language: node_js
node_js:
  - '8'

branches:
  only:
    - master

cache:
  yarn: true
  directories:
    - website/node_modules
    - $HOME/.m2

before_install:
  - npm install -g ts-node
  - git config --global user.name "${GH_NAME}"
  - git config --global user.email "${GH_EMAIL}"
  - echo "machine github.com login ${GH_NAME} password ${GH_TOKEN}" > ~/.netrc

script:
  # Build the website
  - cd website && yarn install && yarn run typedoc && yarn run build && cd -

  # Generate and test NPM bundle
  # TODO - add semantic release, as soon as the team is ready to release
  # See https://github.com/symphonyoss/hubot-symphony as example
  - cd npm-codegen && yarn install && yarn run bundle && yarn run test && cd -

  # Generate and test Java bundle
  # TODO - add 'yarn run publish'
  - cd mvn-codegen && yarn run generate && yarn run bundle && yarn run test && cd -

  # Generate C#
  # TODO - write/run test and generate bundles
  - cd cs-codegen && yarn run quicktype-cs && cd -

  # Generate Python
  # TODO - write/run test and generate bundles
  - cd pypi-codegen && yarn run quicktype-python && cd -

deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GH_TOKEN
    email: $GH_EMAIL
    name: $GH_NAME
    verbose: true
    keep-history: true
    local-dir: website/build/finos-fo
    target_branch: gh-pages
    on:
      branch: master